apiVersion: v1
kind: ConfigMap
metadata:
  name: notifications-config
data:
  DB_HOST: "notification-db"
  DB_NAME: "Db.Notifications"
  ASPNETCORE_ENVIRONMENT: "Development"
  ACCEPT_EULA: "Y"
  MSSQL_PID: "Developer"
