apiVersion: apps/v1
kind: Deployment
metadata:
  name: notifications-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notifications-db
  template:
    metadata:
      labels:
        app: notifications-db
    spec:
      containers:
        - name: notifications-db
          image: mcr.microsoft.com/mssql/server:2022-latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 1435
          env:
            
            - name: ACCEPT_EULA
              valueFrom:
                configMapKeyRef:
                  name: notifications-config
                  key: ACCEPT_EULA
            
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: notifications-secret
                  key: DB_PASSWORD